"""empty message

Revision ID: 4c0f8fd22d64
Revises: None
Create Date: 2016-09-30 00:01:16.039255

"""

# revision identifiers, used by Alembic.
revision = '4c0f8fd22d64'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=32), nullable=True),
    sa.Column('nachname', sa.String(length=32), nullable=True),
    sa.Column('geb', sa.Date(), nullable=True),
    sa.Column('highscore', sa.Integer(), nullable=True),
    sa.Column('savegame', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
