"""empty message

Revision ID: 6e78226005e6
Revises: None
Create Date: 2016-09-30 20:10:26.286404

"""

# revision identifiers, used by Alembic.
revision = '6e78226005e6'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=32), nullable=True),
    sa.Column('nachname', sa.String(length=32), nullable=True),
    sa.Column('geb', sa.Date(), nullable=True),
    sa.Column('highscore', sa.Integer(), nullable=True),
    sa.Column('savegame', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
